<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error 404</title>
</head>
<body>
    <div class="container-fluid">
        <div class="m-4 p-4 container">
            <span><h1 class="fs-2 fw-bold text-danger">Error <small class="text-warning text-muted">404</small></h1></span>
            <p class="">
                Page not Found
            </p>
            <p>
                <a class="p-3 btn-primary rounded text-light fs-3 text-decoration-none" href="<?php echo URL_PATH;?>">Back to Home</a>
            </p>
        </div>
    </div>
</body>
</html>